import { Info } from "lucide-react";

import type { RiskResult } from "@/lib/types";

export function RiskExplanation({ risk }: { risk: RiskResult }) {
  return (
    <div className="space-y-4">
      <p className="text-sm leading-relaxed text-foreground/90">{risk.explanation}</p>

      <div className="rounded-lg border border-border bg-background/40 p-3">
        <div className="eyebrow">Primary signal</div>
        <div className="mt-1 text-sm font-medium">{risk.primarySignal}</div>
      </div>

      {risk.secondarySignals.length > 0 && (
        <div>
          <div className="eyebrow">Secondary signals</div>
          <ul className="mt-2 flex flex-wrap gap-2">
            {risk.secondarySignals.map((s) => (
              <li
                key={s}
                className="rounded-full border border-analytic/25 bg-analytic/10 px-2.5 py-1 text-xs text-analytic"
              >
                {s}
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex items-start gap-2 rounded-lg border border-border bg-muted/40 p-3 text-xs text-muted-foreground">
        <Info className="mt-0.5 size-3.5 shrink-0" />
        <span>
          Generated by the <strong className="font-semibold text-foreground">Baseline Risk Engine</strong> — a
          transparent, deterministic scoring model. This is not a machine-learning prediction and reports no
          experimental accuracy.
        </span>
      </div>
    </div>
  );
}
