/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SprintsIndexRouteImport } from './routes/sprints.index'
import { Route as SprintsSprintIdRouteImport } from './routes/sprints.$sprintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsIndexRoute = SprintsIndexRouteImport.update({
  id: '/sprints/',
  path: '/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsSprintIdRoute = SprintsSprintIdRouteImport.update({
  id: '/sprints/$sprintId',
  path: '/sprints/$sprintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sprints/$sprintId': typeof SprintsSprintIdRoute
  '/sprints/': typeof SprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sprints/$sprintId': typeof SprintsSprintIdRoute
  '/sprints': typeof SprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sprints/$sprintId': typeof SprintsSprintIdRoute
  '/sprints/': typeof SprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/sprints/$sprintId' | '/sprints/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/sprints/$sprintId' | '/sprints'
  id: '__root__' | '/' | '/dashboard' | '/sprints/$sprintId' | '/sprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SprintsSprintIdRoute: typeof SprintsSprintIdRoute
  SprintsIndexRoute: typeof SprintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints/': {
      id: '/sprints/'
      path: '/sprints'
      fullPath: '/sprints/'
      preLoaderRoute: typeof SprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints/$sprintId': {
      id: '/sprints/$sprintId'
      path: '/sprints/$sprintId'
      fullPath: '/sprints/$sprintId'
      preLoaderRoute: typeof SprintsSprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SprintsSprintIdRoute: SprintsSprintIdRoute,
  SprintsIndexRoute: SprintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
